services:
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - "27017:27017"

    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}

    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    logging:
      #limit logs to 200MB (4 rotations of 50M each)
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

    networks:
      - app-network

    depends_on: [ mongo, postgres ]

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    depends_on:
      - redis
    ports:
      - "5540:5540"

    volumes:
      - redis-insight:/data

    networks:
      - app-network

  api-countries:
    build:
      context: ./api-countries
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_URL}
      KAFKA_URL: ${KAFKA_URL}
      COUNTRY_URL: ${COUNTRY_URL}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}

      REDIS_URL: ${REDIS_URL}
      REDIS_PORT: ${REDIS_PORT}

      log_path: /usr/app/logs/application.log

    volumes:
      - logs:/usr/app/logs

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    depends_on:
      mongo:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      redis-insight:
        condition: service_started
      broker1:
        condition: service_healthy
      broker2:
        condition: service_healthy
      broker3:
        condition: service_healthy

    networks:
      - app-network

  api-consumer:
    build:
      context: ./api-consumer
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_URL}
      KAFKA_URL: ${KAFKA_URL}

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    depends_on:
      api-countries:
        condition: service_started
      broker1:
        condition: service_healthy
      broker2:
        condition: service_healthy
      broker3:
        condition: service_healthy

    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8091:8091"

    environment:
      COUNTRY_SERVICE_URL: ${COUNTRY_SERVICE_URL}
      CONSUMER_SERVICE_URL: ${CONSUMER_SERVICE_URL}

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    depends_on:
      api-countries:
        condition: service_started

    networks:
      - app-network

  nexus:
    image: sonatype/nexus3:3.76.0
    platform: linux/amd64
    container_name: nexus
    ports:
      - "8081:8081"
    environment:
      NEXUS_SECURITY_INITIAL_PASSWORD: ${NEXUS_SECURITY_INITIAL_PASSWORD}
      NEXUS_SECURITY_RANDOMPASSWORD: false
    volumes:
      - nexus-data:/nexus-data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status" ]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 60s

    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:9090/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app-network

  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app-network

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    ports:
      - "3200:3200"

    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
    volumes:
      - ./infrastructure/tempo/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo_data:/var/tempo

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    user: root
    ports:
      - "9080:9080" # HTTP interface
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP http
    volumes:
      - ./infrastructure/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
    environment:
      GRAFANA_LOKI_URL: http://loki:3100/loki/api/v1/push
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:9080
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_METRICS_ENABLED: "true"

    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
      - nexus-data:/nexus-data

    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_healthy
      tempo:
        condition: service_started
      alloy:
        condition: service_started

    networks:
      - app-network

  broker1:
    image: apache/kafka:latest
    container_name: broker1
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:9094,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'EXTERNAL://localhost:9092,INTERNAL://broker1:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:9093,2@broker2:9093,3@broker3:9093'
      KAFKA_CLUSTER_ID: 'r4zt_wrqTRuT7W2NJsB_GA'

    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server broker1:9094 --list" ]
      interval: 20s
      timeout: 15s
      retries: 5
      start_period: 60s

    networks:
      - app-network

  broker2:
    image: apache/kafka:latest
    container_name: broker2
    restart: always
    ports:
      - "9093:9092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:9094,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'EXTERNAL://localhost:9093,INTERNAL://broker2:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:9093,2@broker2:9093,3@broker3:9093'
      KAFKA_CLUSTER_ID: 'r4zt_wrqTRuT7W2NJsB_GA'

    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server broker2:9094 --list" ]
      interval: 20s
      timeout: 15s
      retries: 5
      start_period: 60s

    networks:
      - app-network

  broker3:
    image: apache/kafka:latest
    container_name: broker3
    restart: always
    ports:
      - "9094:9092"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:9094,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'EXTERNAL://localhost:9094,INTERNAL://broker3:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:9093,2@broker2:9093,3@broker3:9093'
      KAFKA_CLUSTER_ID: 'r4zt_wrqTRuT7W2NJsB_GA'

    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server broker3:9094 --list" ]
      interval: 20s
      timeout: 15s
      retries: 5
      start_period: 60s

    networks:
      - app-network

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui
    container_name: kafka-ui
    restart: always
    ports:
      - "8092:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=broker1:9094,broker2:9094,broker3:9094
      - DYNAMIC_CONFIG_ENABLED=true

    networks:
      - app-network

    depends_on: [ broker1, broker2, broker3 ]

networks:
  app-network:

volumes:
  artifacts:
  postgres-data:
  redis-insight:
  nexus-data:
  loki_data:
  loki_chunks:
  loki_index:
  loki_rules:
  grafana-data:
  tempo_data:
  logs:


