global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: api-countries
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'api-countries:8080' ]

  - job_name: api-consumer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'api-consumer:8081' ]

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'api-gateway:8091' ]

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: [ 'grafana:3000' ]

  - job_name: alloy
    metrics_path: /metrics
    static_configs:
      - targets: [ 'alloy:9080' ]

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: tempo
    metrics_path: /metrics
    static_configs:
      - targets: [ 'tempo:3200' ]