server:
  port: ${port:8080}

spring:
  datasource:
    url: ${datasource.url:jdbc:postgresql://localhost:5432/${POSTGRES_DB}}
    username: ${datasource.username:${POSTGRES_USER}}
    password: ${datasource.password:${POSTGRES_PASSWORD}}
  sql:
    init:
      mode: always
      platform: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: ${mongo.port:${MONGO_PORT}}
      database: ${mongo.database:${MONGO_DB}}
    redis:
      host:
        localhost
      port:
        6379

  kafka:
    producer:
      acks: all
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
        retries: 2147483647
        delivery.timeout.ms: 120000

country:
  url: ${COUNTRY_URL}

topic:
  name: sandbox