server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always
      platform: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DB}
    redis:
      host:
        ${REDIS_URL}
      port:
        ${REDIS_PORT}

  kafka:
    producer:
      acks: all
      bootstrap-servers: ${KAFKA_URL}
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
        retries: 2147483647
        delivery.timeout.ms: 120000

country:
  url: ${COUNTRY_URL}

topic:
  name: sandbox

security:
  jwt:
    token:
      secret-key: my-secret-key

http:
  auth-token-header-name: X-API-KEY
  auth-token: test123