name: CI - PR Validation (api-gateway) 👔
on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api-consumer
    steps:
      - name: 🧐 Checkout Code
        uses: actions/checkout@v3

      - name: 👨‍🔧 Setup Java 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: 🚀 Build and Test Backend
        run: gradle clean build test
