name: CI - PR Validation (api-countries) 🥇
on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api-countries
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_HOST: ${MONGO_HOST}
          MONGO_PORT: ${MONGO_PORT}
          MONGO_DB: ${MONGO_DB}

        options: >-
          --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name mongo_container

    steps:
      - name: 🧐 Checkout Code
        uses: actions/checkout@v3

      - name: 🚀 Wait for Postgres to be ready
        run: |
          for i in {1..30}; do
            if pg_isready -h 127.0.0.1 -p 5432 -U postgres; then
              echo "Postgres is up!";
              break;
            fi
            echo "Waiting for Postgres...";
            sleep 1;
          done

      - name: 🚀 Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            if mongosh --eval "db.adminCommand('ping'); exit();" ; then
              echo "MongoDB is up!";
              break;
            fi
            echo "Waiting for MongoDB...";
            sleep 1;
          done

      - name: 👨‍🔧 Setup Java 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: 🧳 Set environment variables
        run: |
          echo "NEXUS_URL=${{ secrets.NEXUS_URL }}" >> .env
          echo "NEXUS_USER=${{ secrets.NEXUS_USER }}" >> .env
          echo "NEXUS_PASSWORD=${{ secrets.NEXUS_PASSWORD }}" >> .env

      - name: 🚀 Build and Test Backend
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_PORT: ${{ secrets.MONGO_PORT }}
          MONGO_DB: ${{ secrets.MONGO_DB }}

        run: gradle clean build test
